# Generated by Django 3.2 on 2021-09-03 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20210902_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '栏目'},
        ),
        migrations.AddField(
            model_name='articlepost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='栏目标题'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.articlecolumn', verbose_name='文章栏目'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='最新更新时间'),
        ),
    ]
